replicaCount: 2

namespace: rv-constructions

image:
  repository: achievermithu/rv-constructions
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80

containerPort: 80