sonar.projectKey=rv-constructions
sonar.projectName=RV Constructions Website
sonar.projectVersion=1.0

sonar.sources=app

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/images/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif