apiVersion: apps/v1

kind: Deployment

metadata:
  name: rv-constructions
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: rv-constructions

  template:
    metadata:
      labels:
        app: rv-constructions

    spec:
      containers:
        - name: rv-constructions

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}