pipeline {
    agent any

    stages {
        stage('Print Workspace') {
            steps {
                sh '''
                    echo "Current Directory:"
                    pwd

                    echo ""
                    echo "Workspace Files:"
                    ls -la

                    echo ""
                    echo "App Folder:"
                    ls -la app
                '''
            }
        }

        stage('HTML Validation') {
            steps {
                sh '''
                htmlhint app/*.html --config lint/.htmlhintrc
                '''
            }
        }

        stage('CSS Validation') {
            steps {
                script {
                    def status = sh(
                script: '''
                    stylelint app/css/style.css \
                    --fix \
                    --config lint/.stylelintrc.json
                ''',
                returnStatus: true
            )

                    if (status != 0) {
                        echo 'Stylelint found issues. Continuing pipeline...'
                    }
                }
            }
        }
    }
}
