pipeline {
    agent any

    environment {
        SCANNER_HOME = tool 'SonarScanner'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

    // stages {
    //     stage('Print Workspace') {
    //         steps {
    //             sh '''
    //                 echo "Current Directory:"
    //                 pwd

    //                 echo ""
    //                 echo "Workspace Files:"
    //                 ls -la

    //                 echo ""
    //                 echo "App Folder:"
    //                 ls -la app
    //             '''
    //         }
    //     }

        stage('HTML Validation') {
            steps {
                sh '''
                htmlhint app/*.html --config lint/.htmlhintrc
                '''
            }
        }

        stage('CSS Validation') {
            steps {
                script {
                    def status = sh(
                script: '''
                    stylelint app/css/style.css \
                    --fix \
                    --config lint/.stylelintrc.json
                ''',
                returnStatus: true
            )

                    if (status != 0) {
                        echo 'Stylelint found issues. Continuing pipeline...'
                    }
                }
            }
        }

        stage('JavaScript Validation') {
            steps {
                sh '''
                    eslint app/js/*.js \
                    --config lint/.eslintrc.json || true
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dproject.settings=sonar/sonar-project.properties
                        '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Debug') {
            steps {
                sh '''
                echo "Current User:"
                whoami

                echo ""
                id

                echo ""
                ls -l /var/run/docker.sock

                echo ""
                docker version || true

                echo ""
                docker ps || true
            '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build \
                    -f docker/Dockerfile \
                    -t rv-constructions:${BUILD_NUMBER} \
                    -t rv-constructions:latest .
                '''
            }
        }

        stage('Verify Docker Image') {
            steps {
                sh '''
                    docker images | grep rv-constructions
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                    docker rm -f rv-constructions || true

                    docker run -d \
                    --name rv-constructions \
                    -p 8082:80 \
                    rv-constructions:${BUILD_NUMBER}

                    docker ps
                '''
            }
        }

        stage('Health Check') {
            steps {
                sh '''
                    echo "Waiting for application..."

                    i=1

                    while [ $i -le 15 ]
                    do
                        if curl -f http://host.docker.internal:8082 >/dev/null 2>&1
                        then
                            echo "Application is UP"
                            exit 0
                        fi

                        echo "Retry $i..."
                        sleep 2

                        i=$((i+1))
                    done

                    echo "Application failed to start"

                    docker logs rv-constructions

                exit 1
            '''
            }
        }

    }

    post {
            success {
                echo 'Deployment Successful'
            }

            failure {
                echo 'Deployment Failed'
            }

            always {
                sh '''
                docker image prune -f
                '''
                cleanWs()
            }
    }
    }
